### PR TITLE
Consistently rename AppWrapper phase to state

### PR DESCRIPTION
**Pull request by tardieu**
This PR aligns the go type and field names from `Phase` to `State` to match the serialized name `state`.

### CODE REVIEW

**Comment by tardieu** [comment]
AFAIK `Deleted` is not used in V1, whereas `RunningHoldCompletion` is used. Is `RunningHoldCompletion` required by InstaScale? @asm582

**Comment by dgrove-oss** [comment]
It looks to me like InstaScale is dependent on two things:
 1. Tests against completed like (https://github.com/project-codeflare/instascale/blob/main/controllers/appwrapper_controller.go#L112). 
 2. Tests against not being enqueued (https://github.com/project-codeflare/instascale/blob/main/controllers/appwrapper_controller.go#L287)

**Comment by asm582** [comment]
For the initial cut, I think we should implement integration with Pending and Completed.
- Pending:
 If the state is Pending and the condition is "insufficient resources" InstaScale will scale up. If the state is pending and the condition is "insufficient quota" InstaScale will not scale up. 
- Completed:
 if AW is completed all resources are scaled-down for target AW. if reuse is enabled InstaScale checks if it can transfer resources of previous AW to next AW.

**Comment by tardieu** [comment]
I vote for dealing with constant names (if at all) in a separate PR. The constant values "Pending" and "Completed" already match v1.

**Review by dgrove-oss — APPROVED** [review]

**Pull request merged**
